image: haskell

variables:
  STACK_ROOT: "${CI_PROJECT_DIR}/.stack"

cache:
  paths:
    - .stack-work
    - .stack

before_script:
  - apt update
  - apt install -y xz-utils make libwxgtk3.0-dev
  - stack setup

build:
  script:
    - stack build
