name:                mental-math
version:             0.2.0.0
git:                 https://gitlab.com/concavegit/mental-math
license:             MIT
author:              Kawin Nikomborirak
maintainer:          concavegit@gmail.com
copyright:           2017 Kawin Nikomborirak
homepage:            https://gitlab.com/concavegit/mental-math#readme
bug-reports:         https://gitlab.com/concavegit/mental-math/issues

extra-source-files:
- README.org
- ChangeLog.md

synopsis:            A package for me to practice FRP and mental math
category:            Math

description:         Please see the README on Gitlab at <https://gitlab.com/concavegit/mental-math#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- random
- reactive-banana
- reactive-banana-wx
- wx

library:
  source-dirs: src
  ghc-options:
    - -Wall

executables:
  mental-math-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mental-math

tests:
  mental-math-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mental-math
